# Generated by Django 4.2.7 on 2023-11-30 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto', models.FloatField()),
                ('data_final', models.DateField()),
                ('data_inicial', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco', models.FloatField()),
                ('modelo', models.CharField(max_length=255)),
                ('campo', models.ManyToManyField(to='bd.campo')),
                ('promocao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.promocao')),
            ],
        ),
    ]
